
DOMAIN(PHYSICAL_CHIP, 0x01, chip)
DOMAIN(PHYSICAL_CORE, 0x02, core)
DOMAIN(VIRTUAL_PROCESSOR_HOME_CORE, 0x03, vcpu)
DOMAIN(VIRTUAL_PROCESSOR_HOME_CHIP, 0x04, vcpu)
DOMAIN(VIRTUAL_PROCESSOR_HOME_NODE, 0x05, vcpu)
DOMAIN(VIRTUAL_PROCESSOR_REMOTE_NODE, 0x06, vcpu)
