
DOMAIN(PHYSICAL_CHIP, 0x01)
DOMAIN(PHYSICAL_CORE, 0x02)
DOMAIN(VIRTUAL_PROCESSOR_HOME_CORE, 0x03)
DOMAIN(VIRTUAL_PROCESSOR_HOME_CHIP, 0x04)
DOMAIN(VIRTUAL_PROCESSOR_HOME_NODE, 0x05)
DOMAIN(VIRTUAL_PROCESSOR_REMOTE_NODE, 0x06)
